Repository 104corp/college.104.com.tw, pull requests merged in 2023-12, with the labels that each got.

#54 ITPMSOEDREQ-2329
  package.json
  src/apis/home/internJobList.js
  src/apis/home/partTimeJobList.js
  src/stores/Job.js
  src/views/Index/components/SectionCover.vue
  test/apis/home/internJobList.test.js
  test/apis/home/partTimeJobList.test.js
  test/stores/Job.test.js
Labels: staging

#56 CSROP-4159 - [功能] 調整gtm
  src/views/Index/components/SectionCover.vue
Labels: feature

#57 CSROP-4164 - [功能] 更多按鈕gtm設定
  src/views/Index/components/SectionCover.vue
Labels: feature

#58 ITPMSOEDREQ-2397
  buildspec.yml
  package.json
  src/views/Index/components/SectionCover.vue
Labels: develop

#59 ITPMSOEDREQ-2397
  buildspec.yml
  package.json
  src/views/Index/components/SectionCover.vue
Labels: staging

#60 [需簽核] ITPMSOEDREQ-2397
  buildspec.yml
  package.json
  src/views/Index/components/SectionCover.vue
Labels: production

#61 [CSROP-4191] 人力銀行連結調整
  src/components/GlobalHeader.vue
Labels: feature

#62 CSROP-4190
  .github/104z-workflows/buildspec_develop.yml
  .github/104z-workflows/buildspec_preview.yml
  .github/104z-workflows/buildspec_production.yml
  .github/104z-workflows/buildspec_staging.yml
  buildspec.yml
  package.json
  script/buildspec_preview.yml
  src/components/GlobalHeader.vue
Labels: develop

#63 CSROP-4190
  .github/104z-workflows/buildspec_develop.yml
  .github/104z-workflows/buildspec_production.yml
  .github/104z-workflows/buildspec_staging.yml
Labels: develop

#64 ITPMSOEDREQ-2428
  .github/104z-workflows/buildspec_develop.yml
  .github/104z-workflows/buildspec_preview.yml
  .github/104z-workflows/buildspec_production.yml
  .github/104z-workflows/buildspec_staging.yml
  buildspec.yml
  package.json
  script/buildspec_preview.yml
  src/components/GlobalHeader.vue
Labels: staging

#65 [需簽核] ITPMSOEDREQ-2428
  .github/104z-workflows/buildspec_develop.yml
  .github/104z-workflows/buildspec_preview.yml
  .github/104z-workflows/buildspec_production.yml
  .github/104z-workflows/buildspec_staging.yml
  buildspec.yml
  package.json
  script/buildspec_preview.yml
  src/components/GlobalHeader.vue
Labels: production
